### PR TITLE
Client telemetry

### LINKED ISSUE #46: Move telemetry to client-side
## Description
Move telemetry to client-side, so that it is more useful.

Do not forget to change the documentation/readme/everywhere

## Test plans
N/A

## Additional Information
None

## Checklist
- [x] This issue concerns BlindAI Client
- [x] This issue concerns BlindAI Server

### PR DESCRIPTION
**Pull request by cchudant**
## Description

Here are the info it collects:

For every event,
- `uid` is a unique id created by taking the sha256 of the hostname and username of the machine
- `platform`, composed of os, release, version, arch. Example: 
  - os: Linux/Windows
  - release: 5.13.19-2-MANJARO on my machine
  - version: SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 on my machine (kernel/windows version)
  - arch: x86_64
- the time

Event list:
```py
class ConnectEvent(Event):
    simulation: bool
    policy_allow_debug: Optional[bool]
    server_sgx_enabled: bool
    server_platform: str
    server_version: str
class SendModelEvent(Event):
    simulation: bool
    policy_allow_debug: Optional[bool]
    server_sgx_enabled: bool
    server_platform: str
    server_version: str
    sign: bool
class RunModelEvent(Event):
    simulation: bool
    policy_allow_debug: Optional[bool]
    server_sgx_enabled: bool
    server_platform: str
    server_version: str
    sign: bool
```

`server_platform`, `server_platform` and `server_version` are sent by the server to the client using the `GetServerInfo` call.

This builds upon #48, so i expect conflicts if #48 gets new commits.

## Questions

- Should we remove the server-side telemetry?
- Are the infos I collect here enough / too much?
- I am making a call to amplitude every time the client connects/send_model/run_model
  - this makes me worry about performance, since we don't batch events, we send them one at a time at every request..
  - also, connect/send_model/run_model has to block until the amplitude request is fully sent, nothing is done in the background and it's fully synchronous 
  - maybe there is a better way => an alternative is to send more info to the server when doing a request (like the client uid for example, client version, client platform..)
    - this may mean we don't have to do client-side telemetry, which imo is a better idea? what do you think
- I then need to update the documentation (docs / readme / everywhere we talk about telemetry)

These questions will need to get answered before I can make more progress :)
@dhuynh95 @JoFrost 

## Related Issue

Closes #46 

## Type of change

- [x] This change requires a documentation update
- [x] This change affects the client
- [x] This change affects the server
- [ ] This change affects the API
- [ ] This change only concerns the documentation

## How Has This Been Tested?

Tested locally and using the amplitude dashboard, and it works :)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have updated the documentation according to my changes

<!-- 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
-- >

### CODE REVIEW

**Comment by dhuynh95** [comment]
_Should we remove the server-side telemetry?_ 
> If we have information on the client side whether the server side is in hardware / simulation, then I guess no need to keep track on the server side.

_Are the infos I collect here enough / too much?_
> Seems good. Could you collect the name and size of the model as well? We might collect later a hash of the model name, but knowing what kind of model runs could greatly help us know what kind of models we should focus on.

_I am making a call to amplitude every time the client connects/send_model/run_model_ 
> I see your point. Could we do it async? We could also send info from the client and let the server upload telemetry yes.

**Comment by JoFrost** [comment]
>  alternative is to send more info to the server when doing a request (like the client uid for example, client version, client platform..)
Imo this is the best.

**Comment by cchudant** [comment]
Hello
I have changed the implementation completely.
There is no client-side telemetry, but there is a ClientInfo field that is given to the server in the requests
Here all the info collected:
```js
{
    "user_id": "9AD129C4F336C926", // hash of the hostname and username of the server
    "event_type": "send_model",
    "device_id": "Linux - SGX SW",
    "time": 1650024051, // unix time in seconds
    "app_version": "0.3.0",
    "user_properties": {
        "sgx_mode": "SW",
        "uptime": 10, // in seconds
        "azure_dcsv3_patch_enabled": false,
        "client_uid": "cf342e4cf7384a4e6547d821d5a49f4b4601f0d69e01dfaf6aeb1e8a3addb75e", // hash of hostname and username of the client
        "client_platform_name": "Linux",
        "client_platform_arch": "x86_64",
        "client_platform_version": "#1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021",
        "client_platform_release": "5.13.19-2-MANJARO",
        "client_user_agent": "blindai_python",
        "client_user_agent_version": "0.3.0"
    },
    "event_properties": /* depends on the event */
}
```
Notable changes:
- add azure_dcsv3_patch_enabled which is nice to have
- add client_user_agent for future clients

Here are the per-event infos:
```rs
pub enum TelemetryEventProps {
    Started {}, // server started
    SendModel {
        model_name: Option<String>,
        model_size: usize,
    },
    RunModel {
        model_name: Option<String>,
    },
}
```

I need to update the docs & readme before merging

Also, I am thinking about adding timing info (how much did a request take) to the telemetry. This will be important when we will focus more on speed.
And, print some of the fields (client user agent and version, timing infos) to the console. That would be much better than the logging we currently have.

**Comment by cchudant** [comment]
Changed the console messages, added timing info to the console and telemetry

```
[INFO  blindai_sgx::client_communication] [blindai_python 0.3.0] SendModel successful in 510ms (name=COVID-Net-CXR-2.onnx, size=35023355, sign=false)
[INFO  blindai_sgx::client_communication] [blindai_python 0.3.0] RunModel successful in 572ms (name=COVID-Net-CXR-2.onnx, sign=false)
```

**Review by JoFrost — APPROVED** [review]
OK

**Pull request merged**
