### PR TITLE
Dev client exceptions

### PR DESCRIPTION
**Pull request by CerineBnsd**
### Added exception handling to the connect_server method
This pull request eliminates the boolean that was returned by the connect_server method and raises exceptions when errors occur.

- Different errors are mapped to different exceptions types (see errors.py ) with custom error messages according to the action that raised the error. 
- `setdefauttimeout` is added before ssl.get_server_certificate, to handle cases when the server name exists but is not the correct one (doesn't correspond to a blindai server)
- Debug mode allows seeing the whole error traceback and the original exception. 

### To do after validation
- Edit documentation accordingly
- Decide wether to raise exceptions in the other methods also, or to edit reply.ok to false (as it is right now)

### CODE REVIEW

**Comment by JoFrost** [comment]
Good work, what you suggest as changes looks good to me. However, before we can consider the merge, please update the Docstring to reflect the changes, and please use Python Black on the code. We will ignore all the others CI checks for now as it needs some tweaks. 
Please remove as well the commit you did on the master branch

**Review by JoFrost — CHANGES_REQUESTED** [review]
Good work, what you suggest as changes looks good to me. However, before we can consider the merge, please update the Docstring to reflect the changes, and please use Python Black on the code. We will ignore all the others CI checks for now as it needs some tweaks.
Please remove as well the commit you did on the master branch

**Comment by CerineBnsd** [comment]
@JoFrost Well noted, thank you. I'll make the requested changes today.

**Comment by JoFrost** [comment]
Closing this pull request, as it no longer makes sense because of the other pull request you made.

**Pull request closed without merging**
