### PR TITLE
change client version files extensions

### PR DESCRIPTION
**Pull request by mbrunel**
## Description

change client version files extensions from .py to .txt

## Related Issue

- These files were used as plaintext and not as python script, so python extension is misleading
- It provoked a bug in the API generation

## Type of change
The types of changes must be deduced from the labels of the related issues. Please consider providing these further details.

- [x] This change requires a documentation update
- [x] This change affects the client

## How Has This Been Tested?

tested by the github actions

### CODE REVIEW

**Comment by mbrunel** [comment]
I misunderstood it a bit, I'll fix it tomorrow

**Comment by JoFrost** [comment]
By renaming version.py to version.txt, you broke the wheel generation part.

**Comment by JoFrost** [comment]
The version.py is called as a module inside the SDK, renaming it to txt might break everything as this file is imported.

**Comment by JoFrost** [comment]
Irrelevant at the moment, closing this PR

**Pull request closed without merging**
