### PR TITLE
feat/client: configurable ports

### PR DESCRIPTION
**Pull request by CerineBnsd**
## Description
Configurable ports numbers in the client side.
## Related Issue
None.
## Type of change
- [X] This change requires a documentation update
- [X] This change affects the client
- [X] This change affects the API (The client interface, not the proto) 

## How Has This Been Tested?

Tested locally with default and custom ports numbers. 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have updated the documentation according to my changes (The changelog file)

### CODE REVIEW

**Review by JoFrost — CHANGES_REQUESTED** [review]
It doesn't seems possible for the user to configure the ports using connect_server. Can you please add that to the connect server method?

**Comment by CerineBnsd** [comment]
> 

it's added, untrusted_port and attested_port are now parameters in connect_server, and can be changed, the default values are kept also in case the user doesn't want to change them, or should it be done otherwise?

**Comment by CerineBnsd** [comment]
> My bad, the review window didn't show this properly.

No problem at all! What about the server part, can the `config.toml` file be injected to the docker image for the moment?

**Comment by JoFrost** [comment]
> > My bad, the review window didn't show this properly.
> 
> No problem at all! @JoFrost What about the server part, can a custom `config.toml` file be injected to the docker image for the moment?

Not at the moment.

**Comment by JoFrost** [comment]
@CerineBnsd Please remember to change the port arguments to unsigned short, so we can merge this! :)

**Comment by CerineBnsd** [comment]
> @CerineBnsd Please remember to change the port arguments to unsigned short, so we can merge this! :)
Do you mean like this? 
```
unsigned_port: str = "50052",
signed_port: str = "50051",
```

**Comment by JoFrost** [comment]
unsigned_port: int = 50052,
signed_port: int = 50051,

Something like this rather

**Pull request closed without merging**
