### PR TITLE
Baas doc update

### PR DESCRIPTION
**Pull request by mbrunel**
Reorganization and update of the docs required by the mithril cloud launch.

This change only concerns the docs.

### CODE REVIEW

**Comment by mbrunel** [comment]
This is only a draft for now as I'm sure there are lots of typos everywhere. This however my intended general structure of the docs. So I want to know now what people think is missing/unclear/wrong.

The malicious image example is not done yet as it is not on the dockerhub.

**Comment by mbrunel** [comment]
I put this branch in active hidden mode on readthedocs so that people can check out what it looks like in real time. here is the link : https://blindai.mithrilsecurity.io/en/baas-doc-update

**Comment by ShannonSD** [comment]
Maybe add an example script along with the explanation for generating different mrenclaves.

**Comment by ShannonSD** [comment]
The trusting blindai section is accurate.

**Review by JoFrost — APPROVED** [review]

**Pull request merged**
