### PR TITLE
Export proofs, python tests and some refactor

### LINKED ISSUE #37: Execution exports
## Description

For the Signed Responses feature (#13) to be useful, we need a way to export and validate execution proofs.

Here is the proposed API:
```py
response = client.run_model(run_inputs, sign=True)
response.save_to_file("./execution_proof.json")
```

```py
from blindai.client import load_execution_file

response = load_execution_file("./proof_of_execution.json")
response.validate(policy_file="./policy.toml") # throws if invalid or execution is not signed
print("The proof is valid!")
```

We should also have these functions:

```py
response.export_binary() :: bytes
from blindai.client import load_execution_binary
response = load_execution_binary(a :: bytes)
```

### Unanswered questions
- Json? CBOR is probably a better choice
- Should `save_to_file` work when sign=False?

## Motivation and Context
For the Signed Responses feature (#13) to be useful, we need a way to export execution proofs.

## Affected Features
Signed Responses feature (#13)

## Test Plans
Add tests and unit-tests.

## Additional Information
None

## Checklist
- [x] This issue concerns BlindAI Client
- [ ] This issue concerns BlindAI Server

### PR DESCRIPTION
**Pull request by cchudant**
## Description

I am sorry this PR is big :sweat_smile: 

- refactor Policy to a proper class
- add typings on a lot of functions and classes, add AttestationError error
- fix python imports (the __init__ hack we used, which caused conflicts on downstream code..)
- moved generated protobuf files to a `client/blindai/pb` instead of `client/blindai` directly
- add a protobuf file, which contains the file format for proof files
- change RunModelResponse & UploadModelResponse classes to proper clean classes
- add SignedResponse which is inherited by RunModelResponse and UploadModelResponse
- new apis on SignedResponse: is_signed, save_to_file, as_bytes, load_from_file, load_from_bytes, validate (see #37)
- change some methods and fields from BlindaiClient to private
- add unittests to python client for send_model and run_model and (they mock the server responses) 
- add unittests to python client for the newly added proof export API surface

### Future work

- CI integration for these new unittests (which are separate from the e2e tests)
- create unittests for dcap_attestation.py (verify_dcap_attestation, verify_claims)

## Related Issue

Closes #37 

## Type of change

- [x] This change requires a documentation update
- [x] This change affects the client
- [ ] This change affects the server
- [ ] This change affects the API
- [ ] This change only concerns the documentation

## How Has This Been Tested?

Added unit tests for the new api surface

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have updated the documentation according to my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cchudant** [comment]
I am confused about why this is not building.. I haven't changed the attestation lib build...

@JoFrost @CerineBnsd do you have any idea?

**Comment by JoFrost** [comment]
You did not change anything in the build process? Did you rename the library somewhere?

**Comment by cchudant** [comment]
> You did not change anything in the build process? Did you rename the library somewhere?
I did not touch anything regarding the build process except adding a protobuf file

**Comment by JoFrost** [comment]
I will test the build process locally

**Comment by CerineBnsd** [comment]
> > You did not change anything in the build process? Did you rename the library somewhere?
> 
> I did not touch anything regarding the build process except adding a protobuf file

I was testing this as well, I used your same 'setup.py' with the master branch and the build happens normally, for some reason, the extension (pybin11 module) is being built before the attestation library and that's why it's failing

**Comment by CerineBnsd** [comment]
> > > You did not change anything in the build process? Did you rename the library somewhere?
> > 
> > 
> > I did not touch anything regarding the build process except adding a protobuf file
> 
> I was testing this as well, I used your same 'setup.py' with the master branch and the build happens normally, for some reason, the extension (pybin11 module) is being built before the attestation library and that's why it's failing, I'll continue seeing with it as well.

@cchudant  You should add an empty '__init__.py' in the blindai folder, 'find_package' function in setup.py will use it to detect that blindai folder is a package.

**Comment by CerineBnsd** [comment]
@cchudant  You should add another one in `utils` folder as well.

**Comment by cchudant** [comment]
Proofs can now be ""verified"" in simulation mode using `allow_simulation_mode=true` in validate()
The CI was not working because i broke simulation mode but now it's fixed

Also, I fixed the fact that you should be able to use simulation mode without policy file, thank you @CerineBnsd for pointing that out :)

**Review by JoFrost — APPROVED** [review]
OK

**Pull request merged**
